---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-socket-deployment
spec:
  selector:
    matchLabels:
      app: react-socket
  replicas: 1
  template:
    metadata:
      labels:
        app: react-socket
    spec:
      containers:
        - name: react-socket
          image: <REGISTRY>/<NAMESPACE>/react-socket:latest
          imagePullPolicy: Always
          ports:
              - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-socket-service
  labels:
    app: react-socket
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: react-socket
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: <glb-name>
 annotations:
   kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
 rules:
 - host: <glb-name>.<your_domain_name>
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service
           name: hello-world-service
           port:
             number: 80
